config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users,
   controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :livres
  resources :articles
  resources :videos
  resources :projets
  get "convictions", to: "pages#convictions"
  get "competences", to: "pages#competences"
  get "ressources", to: "pages#ressources"
  get "projets", to: "pages#projets"
  get "bibliotheque", to: "pages#bibliotheque"
  get "articles", to: "pages#articles"
  get "videos", to: "pages#videos"
  get "prehome", to: "pages#prehome"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :picture, presence: true
end

app/models/livre.rb
class Livre < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :author, presence: true
  validates :url, presence: true
  validates :description, presence: true
  validates :picture, presence: true
end

app/models/projet.rb
class Projet < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :url_projet, presence: true
  validates :background_picture, presence: true
  validates :text, presence: true
  validates :picture_1, presence: true
  validates :picture_2, presence: true
  validates :picture_3, presence: true
  validates :picture_comment_1, presence: true
  validates :picture_comment_2, presence: true
  validates :picture_comment_3, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, omniauth_providers: [:linkedin]
  has_many :articles
  has_many :livres
  has_many :videos
  has_many :projets
end

 def self.find_for_linkedin_oauth(auth)
  user_params = auth.slice("provider", "uid")
  user_params.merge! auth.info.slice("email", "first_name", "last_name")
  user_params[:linkedin_picture_url] = auth.info.image
  user_params[:token] = auth.credentials.token
  user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
  user_params = user_params.to_h

  user = User.find_by(provider: auth.provider, uid: auth.uid)
  user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
  if user
    user.update(user_params)
  else
    user = User.new(user_params)
    user.password = Devise.friendly_token[0, 20] # Fake password for validation
    user.save
  end

  return user
  end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:prehome]
  include Pundit

  # Pundit: white-list approach.

  # WARNING commente les 2 lignes en dessous ca desactive toutes les policies !!!!!!!!!!!!!!
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Seules les personnes connectées peuvent accéder aux projets"
    redirect_to(user_session_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @articles = Article.all
    @articles = policy_scope(Article)
  end

  def show
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.save
    redirect_to articles_path
    authorize @article
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
    authorize @article
  end

  def article_params
    params.require(:article).permit(:title, :url, :description, :picture)
  end
end

app/controllers/livres_controller.rb
class LivresController < ApplicationController
  before_action :set_livre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @livres = Livre.all
    @livres = policy_scope(Livre)
  end

  def show
  end

  def new
    @livre = Livre.new
    authorize @livre
  end

  def create
    @livre = current_user.livres.build(livre_params)
    @livre.save
    redirect_to livres_path
    authorize @livre
  end

  def edit
  end

  def update
    @livre.update(livre_params)
    redirect_to livres_path
  end

  def destroy
    @livre.destroy
    redirect_to livres_path
  end

  private

  def set_livre
    @livre = Livre.find(params[:id])
    authorize @livre
  end

  def livre_params
    params.require(:livre).permit(:title, :author, :url, :description, :picture)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :convictions, :competences, :ressources, :projets, :bibliotheque, :articles, :videos]
  skip_after_action :verify_authorized
  def home
  end

  def prehome
    render :layout => false
  end

  def convictions
  end

  def competences
  end

  def ressources
  end

  def projets
  end

  def bibliotheque
  end

  def articles
  end

  def videos
  end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  before_action :set_projet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @projets = Projet.all
    @projets = policy_scope(Projet)
  end

  def show
  end

  def new
    @projet = Projet.new
    authorize @projet
  end

  def create
    @projet = current_user.projets.build(projet_params)
    @projet.save
    redirect_to projets_path
    authorize @projet
  end

  def edit
  end

  def update
    @projet.update(projet_params)
    redirect_to projets_path
  end

  def destroy
    @projet.destroy
    redirect_to projets_path
  end

  private

  def set_projet
    @projet = Projet.find(params[:id])
    authorize @projet
  end

  def projet_params
    params.require(:projet).permit(:title, :description, :url_projet, :background_picture, :text, :picture_1, :picture_2, :picture_3, :picture_comment_1, :picture_comment_2, :picture_comment_3)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def linkedin
    user = User.find_for_linkedin_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Linkedin') if is_navigational_format?
    else
      session['devise.linkedin_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @videos = Video.all
    @videos = policy_scope(Video)
  end

  def show
  end

  def new
    @video = Video.new
    authorize @video
  end

  def create
    @video = current_user.videos.build(video_params)
    @video.save
    redirect_to videos_path
    authorize @video
  end

  def edit
  end

  def update
    @video.update(video_params)
    redirect_to videos_path
  end

  def destroy
    @video.destroy
    redirect_to videos_path
  end

  private

  def set_video
    @video = Video.find(params[:id])
    authorize @video
  end

  def video_params
    params.require(:video).permit(:title, :url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>

  <%= f.label :title, "Entrer le titre" %>
  <%= f.text_field :title %>

  <%= f.label :description, "Entrer la description" %>
  <%= f.text_field :description %>

  <%= f.label :url, "Entrer l'url" %>
  <%= f.text_field :url %>

  <%= f.label :picture, "Entrer l'url d'une photo" %>
  <%= f.text_field :picture %>

  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="container">
  <h1 id="green">Mes articles :</h1>
  <% if policy(Article).create? %>
  <%= link_to "Ajouter un article", new_article_path, class: "btn btn-flat" %>
<% end %>
</div>




<div class="container">
<% @articles.each do |article| %>
<a target="_blank" href="<%= article.url %>">
<div class="card-trip">
  <img src="<%= article.picture %>" />
  <div class="card-trip-infos">
    <div>
      <h2><%= article.title %></h2>
      <p style="color: black"><strong><%= article.description %></strong></p>
      <% if policy(article).edit? %>
      <p><%= link_to 'Edit', edit_article_path(article) %></p>
      <% end %>
      <% if policy(article).edit? %>
      <p><%= link_to 'Destroy', article, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
      </p>
    </div>
  </div>
</div>
</a>
<% end %>

<%= link_to "Retour Accueil", root_path, :class=>"btn btn-flat", :style=>'color:#000000;' %>
</div>

app/views/articles/new.html.erb
Créer ton nouvel article !

<%= form_for @article do |f| %>

  <%= f.label :title, "Entrez le titre" %>
  <%= f.text_field :title %>

  <%= f.label :description, "Entrez une description" %>
  <%= f.text_field :description %>

  <%= f.label :url, "Entrez l'url medium" %>
  <%= f.text_field :url %>

  <%= f.label :picture, "Entrez l'url de la photo" %>
  <%= f.text_field :picture %>

  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<%= link_to "Retour à la bibliothèque", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioQuentin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logonavbar.png') %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-172367700-2"></script>
    <script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/e34cd5678706fb62ae19af198/d7227733b7605276ed182faa7.js");</script>
    <script id="convertful-api" src="https://app.convertful.com/Convertful.js?owner=19660" async></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-172367700-2');
    </script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
</html>

app/views/livres/edit.html.erb
<%= form_for @livre do |f| %>

  <%= f.label :title, "Entrer le titre" %>
  <%= f.text_field :title %>

  <%= f.label :description, "Entrer le résumé du livre" %>
  <%= f.text_field :description %>

  <%= f.label :author, "Entrer le nom de l'auteur" %>
  <%= f.text_field :author %>

  <%= f.label :url, "Entrer l'url amazon" %>
  <%= f.text_field :url %>

  <%= f.label :picture, "Entrer l'url de la photo" %>
  <%= f.text_field :picture %>

  <%= f.submit %>
<% end %>

app/views/livres/index.html.erb
<div class="container">
  <h1 id="green">Binvenue dans ma bibliothèque :</h1>
  <% if policy(Livre).create? %>
    <%= link_to "Ajouter un livre à la bibliothèque", new_livre_path, class: "btn btn-flat" %>
  <% end %>
</div>
<div class="container">
  <div class="cards">
    <%@livres.each do |livre| %>
      <div class="card" style="width: 18em";>
        <img class="card-img-top" src="<%= livre.picture %>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= livre.title %></h5>
          <h6 class="card-title"><u>De <%= livre.author %></u></h6>
          <p class="card-text"><%= livre.description %></p>
          <a target="_blank" href="<%= livre.url %>" class="btn btn-success">plus d'infos
          </a>
          <% if policy(livre).edit? %>
            <p><%= link_to 'Edit', edit_livre_path(livre) %></p>
          <% end %>
          <% if policy(livre).edit? %>
            <p><%= link_to 'Destroy', livre, method: :delete, data: { confirm: "Are you sure?" } %>
            </p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <%= link_to "Retour Accueil", root_path, :class=>"btn btn-flat", :style=>'color:#000000;' %>
</div>

app/views/livres/new.html.erb
<div class="container">
  <%= simple_form_for @livre do |f| %>
    <%= f.input :title %>

    <%= f.input :description %>

    <%= f.input :author %>

    <%= f.input :url %>

    <%= f.input :picture %>

    <div class="btn-flat text-center">
      <%= f.button :submit %>
    </div>
</div>
<% end %>

app/views/livres/show.html.erb
<h2><a target="_blank" href="<%= @livre.url %>"><%= @livre.title %></a></h2>
<p>De <%= @livre.author %></p>
<%= @livre.picture %>
<h4>Description : <%= @livre.description %></h4>
<p><a target="_blank" href="<%= @livre.url %>">Acheter <%= @livre.title %> sur Amazon</a></p>
<p><a HREF="mailto:deleglise.quentin@hotmail.fr">Emprunter ce livre sur Paris</a></p>
<!-- Voir plus tard pour insérer un lien pour le prêts etc... -->
<%= link_to "Retour à la bibliothèque", livres_path, :class=>"btn btn-flat" %>

app/views/pages/competences.html.erb
<h3>Liste de mes compétences :</h3>
<ul>
  <li>Elaboration et mise en place d’un plan marketing.</li>
  <li>Ecoute des problématiques et conseil sur les outils les plus adaptés à vos besoins.</li>
  <li>Trouver, enrichir et contacter des leads (prospects) automatiquement.</li>
  <li>Réalisation de sites webs et pages de ventes / location / vitrines.</li>
  <li>Réalisation de campagnes d’emailing.</li>
  <li>Réalisation de campagnes ADS (google / facebook / Instagram).</li>
  <li>Elaboration et réalisation d’un plan de branding d’une entreprise.</li>
  <li>Automatiser les <a title="tâche répétitive">"Drudgery tasks"</a> ou <a title="tâche répétitive">"Donkey Work".</a></li><!-- CSS afficher les 2 mots en "surbrillance pour les faire mieux apparaitre -->
</ul>

<p>Vous êtes entrepreneur ou travaillez dans une TPE/PME ? <a target="blank" href="https://www.linkedin.com/in/quentin-deleglise-7a4459131/"> discutons de vos problématiques (mon expertise est gratuite).</a>
  <!--Mettre un emoji love / message-->

<p><%= link_to "Retour Home", root_path %></p>

app/views/pages/convictions.html.erb
<h3>Ma vision</h3>

<p>Je pense que les entrepreneurs sont les personnes qui façonnent ce monde, et qu’elles méritent plus de soutien; de reconnaissance et de sécurité dans cet environnement imprévisible.Pour défendre cette cause, j’ai décidé d'accompagner des entrepreneurs et petites entreprises dans leur stratégie digitale. Pour installer une relation de confiance et garantir les meilleurs résultats aux entreprises que j'accompagne, je ne me rémunère qu'en fonction du résultat que j'apporte. Ainsi nous travaillons ensemble, avec des intérêts similaires dans un environnement sain.</p>

<h3>Mes études :</h3>
<p>Mon <a target="blank" href="https://thotismedia.com/dut-tc/">DUT TC</a> (bac +2 marketing / commerce / communication) m'as donné goût au commerce et installé de fortes bases marketing.</p>
<p>Ma <a target="blank" href="https://www.google.com/search?sxsrf=ALeKk0114rH82c-MQweWmdnCB6nbBcgb9A%3A1590268879478&ei=z5PJXq_VHPHRgwe3-4SIAw&q=licence+professionnelle+métiers+de+l%27entrepreneuriat&oq=licence+professionnelle+métiers+de+l%27entrepreneuriat&gs_lcp=CgZwc3ktYWIQAzIECCMQJzIECCMQJzICCAAyAggAMgIIADIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BAgAEEdQhx5YiR9gtyBoAHABeACAAUeIAYoBkgEBMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjv-KGd9crpAhXx6OAKHbc9ATEQ4dUDCAw&uact=5">licence professionnelle MDE</a> (bac +3 gestion d'entreprise) m'as permis de mieux comprendre les problèmatiques rencontrées par les entrepreneurs.</p>
<p>Mon diplôme de <a target="blank" href="https://www.lewagon.com/fr/paris/web-development-course/full-time">concepteur-développeur d'applications web"</a> (équivalent Bac+3/Bac+4) m'as permis de prendre conscience du nombre infini de solutions qu'apporte le web et la programmation.</p>

<h3>Ma personnalité :</h3>

<p>Je suis curieux, timide et réservé.</p>
<p>Je possède un fort esprit analytique, je me fie aux chiffres (data-driven) et-non à mon intuition.</p>
<p>J'aime découvrir, tester et apprendre sur différents sujets (autodidacte).</p>
<p>Je n'aime pas parler de choses abstraites ou sur lesquelles je ne peux pas avoir d'impact.</p>

<h3>Mon potentiel</h3>

<p>La complémentarité de mes études mêlée à ma passion pour le growth-hacking et la gestion de projet me permet d'offrir des solutions optimales et efficaces en toute sécurité.</p>

Vous êtes entrepreneur ou travaillez dans une TPE/PME ? <a target="blank" href="https://www.linkedin.com/in/quentin-deleglise-7a4459131/"> discutons de vos problématiques (mon expertise est gratuite).
  <!--Mettre un emoji love / message-->

<p><%= link_to "Retour Home", root_path %></p>

app/views/pages/prehome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioQuentin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logonavbar.png') %>
  </head>

  <body>
    <div class="linktohome">
      <h1><a href="/" id="siteaccess">Accéder au site</a></h1>
    </div>
    <div class="video-container embed-responsive-16by9">
      <video autoplay="autoplay" muted="muted">
        <source src="https://res.cloudinary.com/asfxgf/video/upload/v1592915231/samples/output_free_2_bzbgaz.mp4"/>
      </video>
    </div>
    <%= yield %>
  </body>
</html>


<!-- Ici c'est pour ajouter du texte par dessus la vidéo, si jamais...
  <div class="container h-100">
    <div class="d-flex h-50 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-3">Quentin DELEGLISE</h1>
        <p class="lead mb-0">Welcome to my portfolio</p>
      </div>
    </div>
  </div>
  -->

app/views/pages/projets.html.erb
<h1>Voici mes différents projets réalisés</h1>

<h3>Le code :</h3>
<p><a target="blank" href="https://github.com/asfxgf">Mon github</a> Pour y trouver certains de mes scripts et exercices.</p> <!-- Insérer logo -->
<p><a target= "blank" href="https://www.youtube.com/watch?v=hb8TT6Z1ptE&t=1302s">Proxy Rungis : </a>2 semaines de projet à résumer en 1 minute 30 ? Pari tenu !</p>

<h3>Le marketing :</h3>
<p>Insertion des projets à venir !</p> <!-- A compléter -->

<h3>Entrepreneuriat :</h3>
<p>Mes projets persos sont top secrets ! Section bientôt disponible</p> <!-- a voir si je met ou pas, c'est pas prioritaire-->

<h3>Freelancing :</h3>
<p>Aucun projet réalisé en freelance aujourd'hui (En cours)</p>

<p><%= link_to "Retour Home", root_path %></p>

app/views/projets/index.html.erb
<div class="container">
  <h1 id="green">Tous mes projets :</h1>
  <% if policy(Article).create? %>
    <%= link_to "Ajouter un projet", new_projet_path, class: "btn btn-flat" %>
  <% end %>
</div>
<div class="container">
<% @projets.each do |projet| %>
<%= link_to projet_path(projet) do %>
<div class="card-trip">
  <img  class="img-card" src="<%= projet.background_picture %>" />
  <div class="card-trip-infos">
    <div>
      <h2 id="green"><%= projet.title %></h2>
      <h3 style="color: black"><strong><%= projet.description %><strong></h3>
      <% if policy(projet).edit? %>
        <p><%= link_to 'Edit', edit_projet_path(projet) %></p>
      <% end %>
      <% if policy(projet).edit? %>
        <p><%= link_to 'Destroy', projet, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div>
</div>
<% end %>
<% end %>

<%= link_to "Retour Accueil", root_path, :class=>"btn btn-flat", :style=>'color:#000000;' %>
</div>

app/views/projets/new.html.erb
<div class="container">
<h1>Créer un nouveau projet</h1>

<%= simple_form_for @projet do |f| %>

  <%= f.input :title %>

  <%= f.input :description %>

  <%= f.input :url_projet %>

  <%= f.input :background_picture %>

  <%= f.input :text %>
  <div class="row">
    <h1> Attention : Garder de grandes photos, et les dimenssionner pareil #cloudinary</h1>
    <div class="col-sm-6">
      <%= f.input :picture_1 %>
    </div>
    <div class="col-sm-6">
      <%= f.input :picture_comment_1 %>
    </div>
    <div class="col-sm-6">
      <%= f.input :picture_2 %>
    </div>
    <div class="col-sm-6">
      <%= f.input :picture_comment_2 %>
    </div>
    <div class="col-sm-6">
      <%= f.input :picture_3 %>
    </div>
    <div class="col-sm-6">
      <%= f.input :picture_comment_3 %>
    </div>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "https://quentin-portfolio.herokuapp.com/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/asfxgf/image/upload/v1592868751/logonavbar_xsjfil.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= link_to "Accueil", root_path, class: "nav-link" %>
      <%= link_to "Projets", projets_path, class: "nav-link" %>
      <%= link_to "Articles", articles_path, class: "nav-link" %>
      <%= link_to "Videos", videos_path, class: "nav-link" %>
      <%= link_to "Ressources", ressources_path, class: "nav-link" %>
      <%= link_to "Bibliothèque", livres_path, class: "nav-link" %>
      <!-- Se connecter / deco -->
      <!--
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/asfxgf/image/upload/v1594915220/Photos%20projets/portfolio/moncompte_vwpiom.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>


          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      -->
    </ul>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container">
  <h1 id="green">Mes videos :</h1>

  <h2 id="green">J'ai pas encore upload mes vidéos, en attendant voici quelques pépites :</h2>


  <% if policy(Video).create? %>
    <%= link_to "Ajouter une vidéo", new_video_path, class: "btn btn-flat" %>
  <% end %>
</div>

<div class="container">
  <% @videos.each do |video| %>
  <div class="card m-3">
    <div class="card-header text-center">
      <h2><%= video.title %></h2>
      <div class="embed-responsive embed-responsive-21by9">
      <iframe width="1280" height="720" src="https://www.youtube.com/embed/<%= video.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
      </iframe>
    </div>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= video.description %></p>
        <footer class="blockquote-footer">Bonne lecture<br></footer>
      </blockquote>
            <% if policy(video).edit? %>
        <p><%= link_to 'Edit', edit_video_path(video) %></p>
      <% end %>
      <% if policy(video).edit? %>
        <p><%= link_to 'Destroy', video, method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>
  </div>
  <% end %>

  <%= link_to "Retour Accueil", root_path, :class=>"btn btn-flat", :style=>'color:#000000;' %>
</div>
</div>

app/views/videos/show.html.erb
<h1>Ici c'est la show de videos</h1>

<%= link_to "Retour à la liste de videos", video_path %>